package acceptance

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/deploymenttheory/go-macos-codesign/pkg/codesign"
	"howett.net/plist"
)

// The binary fixture is independently generated by Apple's plutil. The second
// encoding exercises a different object ordering and reference representation.
func bundlePlistFixture(t *testing.T, app, arch, profile string) {
	t.Helper()
	bundleFixture(t, app, arch)
	if profile == "xml" {
		return
	}
	info := nativeRead(t, filepath.Join(root, "testdata/bundle-plists/Info.plist"))
	if profile == "binary-go" {
		var m map[string]any
		if _, err := plist.Unmarshal(info, &m); err != nil {
			t.Fatal(err)
		}
		var err error
		info, err = plist.Marshal(m, plist.BinaryFormat)
		if err != nil {
			t.Fatal(err)
		}
	}
	bundleWrite(t, app, "Contents/Info.plist", info)
}

func TestPortableBinaryAppBundles(t *testing.T) {
	for _, profile := range []string{"binary", "binary-go"} {
		for _, arch := range []string{"arm64", "x86_64", "universal"} {
			for _, identity := range []string{"adhoc", "rsa"} {
				t.Run(profile+"/"+arch+"/"+identity, func(t *testing.T) {
					app := filepath.Join(t.TempDir(), "Example.app")
					bundlePlistFixture(t, app, arch, profile)
					info := nativeRead(t, filepath.Join(app, "Contents/Info.plist"))
					id, verify := "-", []string{"--verify"}
					if identity == "rsa" {
						id = filepath.Join(root, "testdata/identities/rsa-identity.pem")
						verify = append(verify, "--trust", filepath.Join(root, "testdata/identities/rsa-cert.pem"))
					}
					mustRun(t, binaryPath, "-s", id, "--timestamp=none", app)
					mustRun(t, binaryPath, append(verify, app)...)
					nativeEqual(t, "original binary metadata", nativeRead(t, filepath.Join(app, "Contents/Info.plist")), info)
					if runtime.GOOS == "darwin" {
						mustRun(t, apple(t), "--verify", "--strict", app)
					}
					if export := os.Getenv("MACOSCODESIGN_EXPORT_DIR"); export != "" {
						if err := os.CopyFS(filepath.Join(export, "signed-bundle-"+profile+"-"+identity+"-"+arch+".app"), os.DirFS(app)); err != nil {
							t.Fatal(err)
						}
					}
					attest(t, map[string]any{"profile": profile, "architecture": arch, "identity": identity, "info_sha256": hash(info), "native_strict_verified": runtime.GOOS == "darwin"})
				})
			}
		}
	}
}

func TestAppleBinaryBundleParity(t *testing.T) {
	reference := apple(t)
	for _, profile := range []string{"binary", "binary-go"} {
		for _, arch := range []string{"arm64", "x86_64", "universal"} {
			t.Run(profile+"/"+arch, func(t *testing.T) {
				dir := t.TempDir()
				native, portable := filepath.Join(dir, "Native.app"), filepath.Join(dir, "Go.app")
				bundlePlistFixture(t, native, arch, profile)
				bundlePlistFixture(t, portable, arch, profile)
				info := nativeRead(t, filepath.Join(native, "Contents/Info.plist"))
				mustRun(t, reference, "-s", "-", "--timestamp=none", native)
				mustRun(t, binaryPath, "-s", "-", "--timestamp=none", portable)
				for _, name := range []string{"Contents/Info.plist", "Contents/MacOS/hello", "Contents/_CodeSignature/CodeResources"} {
					nativeEqual(t, name, nativeRead(t, filepath.Join(portable, name)), nativeRead(t, filepath.Join(native, name)))
				}
				nativeEqual(t, "Apple preserves binary metadata", nativeRead(t, filepath.Join(native, "Contents/Info.plist")), info)
				for v := 0; v <= 4; v++ {
					option := "-d" + strings.Repeat("v", v)
					_, want, wantCode := run(t, reference, option, native)
					_, got, gotCode := run(t, binaryPath, option, portable)
					nativePath, err := filepath.EvalSymlinks(filepath.Join(native, "Contents/MacOS/hello"))
					if err != nil {
						t.Fatal(err)
					}
					got = strings.ReplaceAll(got, filepath.Join(portable, "Contents/MacOS/hello"), "<executable>")
					want = strings.ReplaceAll(want, nativePath, "<executable>")
					if gotCode != wantCode || got != want {
						t.Fatalf("display %s: codes %d/%d\nGo:\n%s\nApple:\n%s", option, gotCode, wantCode, got, want)
					}
				}
				mustRun(t, reference, "--verify", "--strict", portable)
				mustRun(t, binaryPath, "--verify", native)
				attest(t, map[string]any{"profile": profile, "architecture": arch, "metadata_preserved": true, "executable_byte_equal": true, "resource_envelope_byte_equal": true, "display_levels": 5, "native_strict_verified": true})
			})
		}
	}
}

func TestBinaryBundleMetadataMutation(t *testing.T) {
	for _, change := range []string{"equivalent-xml", "value", "truncated", "cycle"} {
		t.Run(change, func(t *testing.T) {
			app := filepath.Join(t.TempDir(), "Example.app")
			bundlePlistFixture(t, app, "arm64", "binary")
			info := nativeRead(t, filepath.Join(app, "Contents/Info.plist"))
			mustRun(t, binaryPath, "-s", "-", app)
			var m map[string]any
			if _, err := plist.Unmarshal(info, &m); err != nil {
				t.Fatal(err)
			}
			var data []byte
			var err error
			switch change {
			case "equivalent-xml":
				data, err = plist.Marshal(m, plist.XMLFormat)
			case "value":
				m["CFBundleName"] = "Altered"
				data, err = plist.Marshal(m, plist.BinaryFormat)
			case "truncated":
				data = info[:len(info)-1]
			case "cycle":
				data = bytes.Clone(info)
				// plutil writes the top dictionary first with one-byte refs.
				data[9] = 0
			}
			if err != nil {
				t.Fatal(err)
			}
			bundleWrite(t, app, "Contents/Info.plist", data)
			_, stderr, code := run(t, binaryPath, "--verify", app)
			if code == 0 {
				t.Fatal("Go accepted metadata mutation", stderr)
			}
			if runtime.GOOS == "darwin" {
				_, stderr, code = run(t, apple(t), "--verify", "--strict", app)
				if code == 0 {
					t.Fatal("Apple accepted metadata mutation", stderr)
				}
			}
			attest(t, map[string]any{"mutation": change, "rejected": true, "native_checked": runtime.GOOS == "darwin"})
		})
	}
}

func TestRecordAppleBinaryBundleFixtures(t *testing.T) {
	if os.Getenv("MACOSCODESIGN_RECORD_BINARY_BUNDLES") != "1" {
		t.Skip("opt-in native binary bundle recording")
	}
	reference := apple(t)
	dir := filepath.Join(root, "testdata/bundle-plists")
	if _, err := os.Stat(filepath.Join(dir, "manifest.json")); !os.IsNotExist(err) {
		t.Fatal("refusing to overwrite recorded fixture manifest", err)
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if entry.Name() != "README.md" {
			t.Fatal("refusing to overwrite fixture directory", entry.Name())
		}
	}
	// All standard plist types, extended lengths, UTF-16 and repeated objects.
	xml := strings.Replace(bundleInfo, "</dict>", `<key>Values</key><array><true/><false/><integer>-42</integer><integer>4294967295</integer><real>1.5</real><date>2026-09-20T00:00:00Z</date><data>AAH/</data><string>日本語 😀</string><string>日本語 😀</string><dict><key>nested</key><string>an extended length ASCII string</string></dict></array></dict>`, 1)
	input := filepath.Join(t.TempDir(), "Info.xml")
	if err := os.WriteFile(input, []byte(xml), 0644); err != nil {
		t.Fatal(err)
	}
	mustRun(t, "/usr/bin/plutil", "-convert", "binary1", "-o", filepath.Join(dir, "Info.plist"), input)
	if err := os.WriteFile(filepath.Join(dir, "Info.xml"), []byte(xml), 0644); err != nil {
		t.Fatal(err)
	}
	host, stderr, code := run(t, "/usr/bin/sw_vers")
	if code != 0 {
		t.Fatal(stderr)
	}
	for _, arch := range []string{"arm64", "x86_64", "universal"} {
		app := filepath.Join(t.TempDir(), "Example.app")
		bundlePlistFixture(t, app, arch, "binary")
		mustRun(t, reference, "-s", "-", "--timestamp=none", app)
		mustRun(t, reference, "--verify", "--strict", app)
		if err := os.CopyFS(filepath.Join(dir, arch+".app"), os.DirFS(app)); err != nil {
			t.Fatal(err)
		}
	}
	hashes := map[string]string{}
	err = filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && d.Name() != "README.md" {
			rel, err := filepath.Rel(dir, path)
			if err != nil {
				return err
			}
			hashes[filepath.ToSlash(rel)] = hash(nativeRead(t, path))
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	manifest := map[string]any{"schema": 1, "files": hashes, "host": strings.TrimSpace(host), "codesign_sha256": hash(nativeRead(t, reference)), "plutil_sha256": hash(nativeRead(t, "/usr/bin/plutil")), "source": "acceptance/bundle_plist_test.go: TestRecordAppleBinaryBundleFixtures", "convert_arguments": []string{"-convert", "binary1", "-o", "Info.plist", "Info.xml"}, "sign_arguments": []string{"-s", "-", "--timestamp=none", "<bundle>"}, "verify_arguments": []string{"--verify", "--strict", "<bundle>"}, "native_strict_verified": true}
	b, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "manifest.json"), append(b, '\n'), 0644); err != nil {
		t.Fatal(err)
	}
	fmt.Println("Recorded binary plist and three native app bundles")
}

func TestNativeBinaryBundleFixtures(t *testing.T) {
	for _, arch := range []string{"arm64", "x86_64", "universal"} {
		t.Run(arch, func(t *testing.T) {
			fixture := filepath.Join(root, "testdata/bundle-plists", arch+".app")
			mustRun(t, binaryPath, "--verify", fixture)
			app := filepath.Join(t.TempDir(), "Example.app")
			bundlePlistFixture(t, app, arch, "binary")
			mustRun(t, binaryPath, "-s", "-", app)
			for _, name := range []string{"Contents/Info.plist", "Contents/MacOS/hello", "Contents/_CodeSignature/CodeResources"} {
				nativeEqual(t, name, nativeRead(t, filepath.Join(app, name)), nativeRead(t, filepath.Join(fixture, name)))
			}
			attest(t, map[string]any{"architecture": arch, "native_fixture_byte_equal": true})
		})
	}
}

func TestBinaryResourceEnvelopeNative(t *testing.T) {
	app := filepath.Join(t.TempDir(), "Example.app")
	bundlePlistFixture(t, app, "arm64", "binary")
	mustRun(t, binaryPath, "-s", "-", app)
	path := filepath.Join(app, "Contents/_CodeSignature/CodeResources")
	var m map[string]any
	if _, err := plist.Unmarshal(nativeRead(t, path), &m); err != nil {
		t.Fatal(err)
	}
	resources, err := plist.Marshal(m, plist.BinaryFormat)
	if err != nil {
		t.Fatal(err)
	}
	main := filepath.Join(app, "Contents/MacOS/hello")
	out, err := codesign.SignBytes(context.Background(), nativeRead(t, main), codesign.SignOptions{Force: true, Identifier: "org.example.bundle", InfoPlist: nativeRead(t, filepath.Join(app, "Contents/Info.plist")), Resources: resources})
	if err != nil {
		t.Fatal(err)
	}
	bundleWrite(t, app, "Contents/_CodeSignature/CodeResources", resources)
	bundleWrite(t, app, "Contents/MacOS/hello", out)
	mustRun(t, binaryPath, "--verify", app)
	if runtime.GOOS == "darwin" {
		mustRun(t, apple(t), "--verify", "--strict", app)
	}
	attest(t, map[string]any{"binary_resource_envelope_verified": true, "native_strict_verified": runtime.GOOS == "darwin"})
}
