//go:build ignore

// Generate native ISO-2022-JP mappings; transition observations stay independent
// of the decoder and are replayed through its public API on every host.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode/utf8"
)

func must(e error) {
	if e != nil {
		panic(e)
	}
}
func read(p string) []byte { b, e := os.ReadFile(p); must(e); return b }
func hash(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func main() {
	check := flag.Bool("check", false, "check deterministic generated source")
	flag.Parse()
	data := read("testdata/bundle-removal/plist-iso2022-jp-values.json")
	var c struct {
		Schema int
		Source string `json:"source_sha256"`
		Codecs []struct {
			Name   string
			Table  int
			SHA256 string
		}
		Tables []struct {
			States []struct {
				Name    string
				Prefix  []byte
				Mapping int
			}
			Mappings []struct {
				Values    []*string
				TailValid []bool
			}
		}
	}
	must(json.Unmarshal(data, &c))
	if c.Schema != 1 || c.Source != hash(read("scripts/probe-plist-iso2022-jp.go")) || len(c.Codecs) != 6 || len(c.Tables) != 1 || len(c.Tables[0].States) != 10 || len(c.Tables[0].Mappings) != 5 {
		panic("incomplete/stale native inventory")
	}
	names := []string{"iso-2022-jp", "iso_2022_jp", "iso2022jp", "csiso2022jp", "cp50221", "windows-50221"}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/generate-plist-iso2022-jp.go; DO NOT EDIT.\n// Native corpus SHA-256: %s\npackage plist\n\nvar iso2022JPCharsets=map[string]bool{\n", hash(data))
	for i, c := range c.Codecs {
		if c.Name != names[i] || c.Table != 0 || len(c.SHA256) != 64 {
			panic("unexpected native family")
		}
		fmt.Fprintf(&out, "%q:true,\n", c.Name)
	}
	out.WriteString("}\n")
	scalar := func(v *string) rune {
		if v == nil {
			return -1
		}
		if !utf8.ValidString(*v) || utf8.RuneCountInString(*v) != 1 {
			panic("non-scalar mapping")
		}
		r, _ := utf8.DecodeRuneInString(*v)
		if r > 0xffff {
			panic("non-BMP mapping requires UTF-16 accounting")
		}
		return r
	}
	states := []string{"ascii", "roman", "kana", "jis0208", "jis0212", "ascii-b", "ascii-h", "kana-right", "jis1978", "jis-d"}
	prefixes := []string{"", "\x1b(J", "\x1b(I", "\x1b$B", "\x1b$(D", "\x1b(B", "\x1b(H", "\x1b)I", "\x1b$@", "\x1b$D"}
	h := sha256.New()
	for i, state := range c.Tables[0].States {
		wanted := []int{0, 1, 2, 3, 4, 0, 0, 2, 3, 3}
		if state.Mapping != wanted[i] {
			panic("unexpected state mapping")
		}
		t := c.Tables[0].Mappings[state.Mapping]
		if state.Name != states[i] || string(state.Prefix) != prefixes[i] || len(t.Values) != 196864 || len(t.TailValid) != 196864 {
			panic("incomplete state")
		}
		for n, v := range t.Values {
			if v == nil {
				h.Write([]byte("-\n"))
			} else {
				h.Write([]byte(hex.EncodeToString([]byte("x"+*v+"y")) + "\n"))
			}
			if n < 256 {
				if state.Mapping < 3 {
					scalar(v)
				} else if v != nil {
					panic("incomplete double-byte state accepted")
				}
			}
		}
		for _, v := range t.TailValid {
			if v {
				h.Write([]byte("7365636f6e64\n"))
			} else {
				h.Write([]byte("-\n"))
			}
		}
		for n, v := range t.Values[256:65792] {
			a, b := n>>8, n&255
			if state.Mapping < 3 {
				x, y := t.Values[a], t.Values[b]
				if x == nil || y == nil {
					if v != nil {
						panic("invalid single-byte pair accepted")
					}
				} else if v == nil || *v != *x+*y {
					panic("non-concatenative pair")
				}
			} else {
				low := 0x21
				if state.Mapping == 4 {
					low = 0xa1
				}
				if a < low || a >= low+94 || b < low || b >= low+94 {
					if v != nil {
						panic("mapping outside qualified pair range")
					}
				} else {
					scalar(v)
				}
			}
		}
	}
	for _, c := range c.Codecs {
		if c.SHA256 != hex.EncodeToString(h.Sum(nil)) {
			panic("native digest mismatch")
		}
	}
	out.WriteString("\nvar iso2022JPSingles=[3][256]rune{\n")
	for _, t := range c.Tables[0].Mappings[:3] {
		out.WriteString("{\n")
		for i, v := range t.Values[:256] {
			fmt.Fprintf(&out, "%#x,", scalar(v))
			if i%8 == 7 {
				out.WriteByte('\n')
			}
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	out.WriteString("\n// JIS X 0208 uses 0x21..0x7e; native JIS X 0212 uses 0xa1..0xfe.\nvar iso2022JPPairs=[2][94][94]rune{\n")
	for i, t := range c.Tables[0].Mappings[3:] {
		low := 0x21
		if i == 1 {
			low = 0xa1
		}
		out.WriteString("{\n")
		for a := low; a < low+94; a++ {
			out.WriteString("{\n")
			for b := low; b < low+94; b++ {
				fmt.Fprintf(&out, "%#x,", scalar(t.Values[256+a*256+b]))
				if (b-low)%8 == 7 {
					out.WriteByte('\n')
				}
			}
			out.WriteString("},\n")
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	generated, e := format.Source([]byte(out.String()))
	must(e)
	const path = "pkg/plist/iso2022_jp_tables.go"
	if *check {
		if !bytes.Equal(generated, read(path)) {
			panic("stale generated tables")
		}
	} else {
		must(os.WriteFile(path, generated, 0644))
	}
	fmt.Println("Verified six ISO-2022-JP names, ten state prefixes and all native observation digests")
}
