//go:build ignore

// Generate only mapping data; the independently captured stream cases qualify
// the state machine through the public decoder on every supported host.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode/utf8"
)

func must(e error) {
	if e != nil {
		panic(e)
	}
}
func read(p string) []byte { b, e := os.ReadFile(p); must(e); return b }
func hash(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func main() {
	check := flag.Bool("check", false, "check deterministic generation")
	flag.Parse()
	data := read("testdata/bundle-removal/plist-iso2022-extensions-values.json")
	var c struct {
		Schema int
		Source string `json:"source_sha256"`
		Codecs []struct {
			Name   string
			Table  int
			SHA256 string
		}
		Tables []struct {
			States []struct {
				Name    string
				Prefix  []byte
				Mapping int
			}
			Mappings []struct {
				Values    []*string
				TailValid []bool
			}
		}
	}
	must(json.Unmarshal(data, &c))
	names := []string{"iso-2022-jp-1", "iso_2022_jp_1", "iso2022jp1", "iso-2022-jp-2", "iso_2022_jp_2", "iso2022jp2", "csiso2022jp2"}
	states := []string{"ascii", "roman", "kana", "jis0208", "jis0212", "gb2312", "ksc5601", "latin", "greek", "roman-h", "jis1978", "jis1990", "ascii-b", "latin-designated", "greek-designated"}
	prefixes := []string{"", "\x1b(J", "\x1b(I", "\x1b$B", "\x1b$(D", "\x1b$A", "\x1b$(C", "\x1b.A\x1bN", "\x1b.F\x1bN", "\x1b(H", "\x1b$@", "\x1b&@", "\x1b(B", "\x1b.A", "\x1b.F"}
	if c.Schema != 1 || c.Source != hash(read("scripts/probe-plist-iso2022-extensions.go")) || len(c.Codecs) != 7 || len(c.Tables) != 2 {
		panic("incomplete native inventory")
	}
	var digests []string
	for _, t := range c.Tables {
		if len(t.States) != 15 {
			panic("incomplete state inventory")
		}
		h := sha256.New()
		for i, st := range t.States {
			if st.Name != states[i] || string(st.Prefix) != prefixes[i] || st.Mapping < 0 || st.Mapping >= len(t.Mappings) {
				panic("invalid state")
			}
			m := t.Mappings[st.Mapping]
			n := 65792
			if i == 0 {
				n += 131072
			}
			if len(m.Values) != n || len(m.TailValid) != n {
				panic("incomplete vectors")
			}
			for _, v := range m.Values {
				if v == nil {
					h.Write([]byte("-\n"))
				} else {
					if !utf8.ValidString(*v) {
						panic("invalid native UTF-8")
					}
					h.Write([]byte(hex.EncodeToString([]byte("x"+*v+"y")) + "\n"))
				}
			}
			for _, v := range m.TailValid {
				if v {
					h.Write([]byte("7365636f6e64\n"))
				} else {
					h.Write([]byte("-\n"))
				}
			}
		}
		digests = append(digests, hex.EncodeToString(h.Sum(nil)))
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/generate-plist-iso2022-extensions.go; DO NOT EDIT.\n// Native corpus SHA-256: %s\npackage plist\n\nvar iso2022ExtensionCharsets=map[string]int{\n", hash(data))
	for i, codec := range c.Codecs {
		family := 0
		if i >= 3 {
			family = 1
		}
		if codec.Name != names[i] || codec.Table != family || codec.SHA256 != digests[family] {
			panic("native family/digest mismatch")
		}
		fmt.Fprintf(&out, "%q:%d,\n", codec.Name, family+1)
	}
	out.WriteString("}\n")
	scalar := func(v *string) rune {
		if v == nil {
			return -1
		}
		if !utf8.ValidString(*v) || utf8.RuneCountInString(*v) != 1 {
			panic("non-scalar mapping")
		}
		r, _ := utf8.DecodeRuneInString(*v)
		if r > 0xffff {
			panic("non-BMP mapping requires UTF-16 accounting")
		}
		return r
	}
	// Check both families' shared Japanese planes before retaining one copy.
	for st := 3; st <= 4; st++ {
		for a := 33; a <= 126; a++ {
			for b := 33; b <= 126; b++ {
				i := 256 + a*256 + b
				x := c.Tables[0].Mappings[c.Tables[0].States[st].Mapping].Values[i]
				y := c.Tables[1].Mappings[c.Tables[1].States[st].Mapping].Values[i]
				if scalar(x) != scalar(y) {
					panic("Japanese families diverged")
				}
			}
		}
	}
	out.WriteString("\nvar iso2022ExtensionPairs=[4][94][94]rune{\n")
	for st := 3; st <= 6; st++ {
		m := c.Tables[1].Mappings[c.Tables[1].States[st].Mapping]
		out.WriteString("{\n")
		for a := 33; a <= 126; a++ {
			out.WriteString("{\n")
			for b := 33; b <= 126; b++ {
				fmt.Fprintf(&out, "%#x,", scalar(m.Values[256+a*256+b]))
				if (b-33)%8 == 7 {
					out.WriteByte('\n')
				}
			}
			out.WriteString("},\n")
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	out.WriteString("\nvar iso2022ExtensionGreek=[128]rune{\n")
	m := c.Tables[1].Mappings[c.Tables[1].States[8].Mapping]
	for i, v := range m.Values[:128] {
		fmt.Fprintf(&out, "%#x,", scalar(v))
		if i%8 == 7 {
			out.WriteByte('\n')
		}
	}
	out.WriteString("}\n")
	generated, e := format.Source([]byte(out.String()))
	must(e)
	const path = "pkg/plist/iso2022_extensions_tables.go"
	if *check {
		if !bytes.Equal(generated, read(path)) {
			panic("stale generated extension tables")
		}
	} else {
		must(os.WriteFile(path, generated, 0644))
	}
	fmt.Println("Verified seven names, two families, fifteen states and all native digests")
}
