//go:build ignore

// Generate the native EUC-JP mapping only after validating every captured
// singleton, pair and 0x8f-prefixed triple against stateless segmentation.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode/utf8"
)

func must(e error) {
	if e != nil {
		panic(e)
	}
}
func read(p string) []byte { b, e := os.ReadFile(p); must(e); return b }
func hash(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func main() {
	check := flag.Bool("check", false, "check deterministic generated source")
	flag.Parse()
	data := read("testdata/bundle-removal/plist-euc-jp-values.json")
	var c struct {
		Schema int
		Source string `json:"source_sha256"`
		Codecs []struct {
			Name   string
			Table  int
			SHA256 string
		}
		Tables []struct {
			Singles, Pairs, Triples []*string
			TailValid               []bool
		}
	}
	must(json.Unmarshal(data, &c))
	if c.Schema != 1 || c.Source != hash(read("scripts/probe-plist-euc-jp.go")) || len(c.Codecs) != 8 || len(c.Tables) != 1 {
		panic("incomplete/stale native inventory")
	}
	names := []string{"euc-jp", "euc_jp", "eucjp", "cseucpkdfmtjapanese", "extended_unix_code_packed_format_for_japanese", "x-euc-jp", "cp51932", "windows-51932"}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/generate-plist-euc-jp.go; DO NOT EDIT.\n// Native corpus SHA-256: %s\npackage plist\n\nvar eucJPCharsets = map[string]bool{\n", hash(data))
	for i, c := range c.Codecs {
		if c.Name != names[i] || c.Table != 0 || len(c.SHA256) != 64 {
			panic("unexpected charset family")
		}
		fmt.Fprintf(&out, "%q: true,\n", c.Name)
	}
	out.WriteString("}\n")
	t := c.Tables[0]
	if len(t.Singles) != 256 || len(t.Pairs) != 65536 || len(t.Triples) != 65536 || len(t.TailValid) != 131328 {
		panic("incomplete native table")
	}
	for i, v := range t.Singles {
		if i < 128 {
			if v == nil || *v != string(rune(i)) {
				panic("ASCII mapping differs")
			}
		} else if v != nil {
			panic("non-ASCII singleton accepted")
		}
	}
	scalar := func(v *string) rune {
		if v == nil {
			return -1
		}
		if !utf8.ValidString(*v) || utf8.RuneCountInString(*v) != 1 {
			panic("non-scalar mapping")
		}
		r, _ := utf8.DecodeRuneInString(*v)
		return r
	}
	for i, v := range t.Pairs {
		a, b := i>>8, i&255
		if a < 128 {
			if b < 128 {
				if v == nil || *v != string([]byte{byte(a), byte(b)}) {
					panic("non-concatenative ASCII mapping")
				}
			} else if v != nil {
				panic("incomplete trail accepted")
			}
		} else {
			scalar(v)
		}
	}
	// Native rejects the JIS X 0212 introducer. Do not silently use a generic
	// EUC-JP mapping that would accept these three-byte sequences.
	for _, v := range t.Triples {
		if v != nil {
			panic("native three-byte support requires a different decoder")
		}
	}
	for b := range 256 {
		if t.Pairs[0x8f00+b] != nil {
			panic("three-byte prefix accepted as a pair")
		}
	}
	values := append(append(append([]*string{}, t.Singles...), t.Pairs...), t.Triples...)
	var body, tail strings.Builder
	for i, v := range values {
		if t.TailValid[i] != (v != nil) {
			panic("tail validity differs")
		}
		if v == nil {
			body.WriteString("-\n")
			tail.WriteString("-\n")
		} else {
			body.WriteString(hex.EncodeToString([]byte("x"+*v+"y")) + "\n")
			tail.WriteString("7365636f6e64\n")
		}
	}
	for _, c := range c.Codecs {
		if c.SHA256 != hash([]byte(body.String()+tail.String())) {
			panic("native observation digest differs")
		}
	}
	out.WriteString("\n// Rows are raw lead bytes 0x80..0xff; columns are raw trail bytes.\nvar eucJPPairs = [128][256]rune{\n")
	for a := 128; a < 256; a++ {
		out.WriteString("{\n")
		for b := 0; b < 256; b++ {
			fmt.Fprintf(&out, "%#x,", scalar(t.Pairs[a*256+b]))
			if b%8 == 7 {
				out.WriteByte('\n')
			}
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	generated, e := format.Source([]byte(out.String()))
	must(e)
	const path = "pkg/plist/euc_jp_tables.go"
	if *check {
		if !bytes.Equal(generated, read(path)) {
			panic("stale generated tables")
		}
	} else {
		must(os.WriteFile(path, generated, 0644))
	}
	fmt.Println("Verified eight EUC-JP names and all singleton/pair/triple body/tail observations")
}
