//go:build ignore

// Generate separate native Shift-JIS and Windows Japanese tables. The complete
// one/two-byte corpus must also agree with the decoder's stateless segmentation.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"unicode/utf8"
)

func must(e error) {
	if e != nil {
		panic(e)
	}
}
func read(p string) []byte { b, e := os.ReadFile(p); must(e); return b }
func hash(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func main() {
	check := flag.Bool("check", false, "check deterministic generated source")
	flag.Parse()
	data := read("testdata/bundle-removal/plist-shift-jis-values.json")
	var c struct {
		Schema int
		Source string `json:"source_sha256"`
		Codecs []struct {
			Name   string
			Table  int
			SHA256 string
		}
		Tables []struct {
			Singles, Pairs []*string
			TailValid      []bool
		}
	}
	must(json.Unmarshal(data, &c))
	if c.Schema != 1 || c.Source != hash(read("scripts/probe-plist-shift-jis.go")) || len(c.Codecs) != 8 || len(c.Tables) != 2 {
		panic("incomplete/stale native inventory")
	}
	names := []string{"shift_jis", "shift-jis", "sjis", "ms_kanji", "csshiftjis", "cp932", "windows-31j", "windows-932"}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/generate-plist-shift-jis.go; DO NOT EDIT.\n// Native corpus SHA-256: %s\npackage plist\n\nvar shiftJISCharsets = map[string]int{\n", hash(data))
	for i, entry := range c.Codecs {
		want := 1
		if i == 0 {
			want = 0
		}
		if entry.Name != names[i] || entry.Table != want || len(entry.SHA256) != 64 {
			panic("unexpected charset family")
		}
		fmt.Fprintf(&out, "%q: %d,\n", entry.Name, entry.Table)
	}
	out.WriteString("}\n\nvar shiftJISSingles = [2][256]rune{\n")
	scalar := func(s *string) rune {
		if s == nil {
			return -1
		}
		if !utf8.ValidString(*s) || utf8.RuneCountInString(*s) != 1 {
			panic("non-scalar mapping")
		}
		r, _ := utf8.DecodeRuneInString(*s)
		return r
	}
	lead := func(b int) bool { return b >= 0x81 && b <= 0x9f || b >= 0xe0 && b <= 0xfc }
	for _, t := range c.Tables {
		if len(t.Singles) != 256 || len(t.Pairs) != 65536 || len(t.TailValid) != 65792 {
			panic("incomplete table")
		}
		out.WriteString("{\n")
		for i, v := range t.Singles {
			r := scalar(v)
			if lead(i) && r != -1 {
				panic("lead is not incomplete")
			}
			fmt.Fprintf(&out, "%#x,", r)
			if i%8 == 7 {
				out.WriteByte('\n')
			}
		}
		out.WriteString("},\n")
		for n, v := range append(append([]*string{}, t.Singles...), t.Pairs...) {
			if t.TailValid[n] != (v != nil) {
				panic("tail validity differs")
			}
		}
		for i, v := range t.Pairs {
			a, b := i>>8, i&255
			if lead(a) {
				scalar(v)
				continue
			}
			x, y := t.Singles[a], t.Singles[b]
			if x == nil || y == nil {
				if v != nil {
					panic("invalid sequence accepted")
				}
			} else if v == nil || *v != *x+*y {
				panic("stateful mapping requires a different decoder")
			}
		}
	}
	out.WriteString("}\n\n// Lead rows: 0x81..0x9f, then 0xe0..0xfc; columns are raw trail bytes.\nvar shiftJISPairs = [2][60][256]rune{\n")
	for _, t := range c.Tables {
		out.WriteString("{\n")
		for a := 0; a < 256; a++ {
			if !lead(a) {
				continue
			}
			out.WriteString("{\n")
			for b := 0; b < 256; b++ {
				fmt.Fprintf(&out, "%#x,", scalar(t.Pairs[a*256+b]))
				if b%8 == 7 {
					out.WriteByte('\n')
				}
			}
			out.WriteString("},\n")
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	generated, e := format.Source([]byte(out.String()))
	must(e)
	const path = "pkg/plist/shift_jis_tables.go"
	if *check {
		if !bytes.Equal(generated, read(path)) {
			panic("stale generated tables")
		}
	} else {
		must(os.WriteFile(path, generated, 0644))
	}
	fmt.Println("Verified eight charset names, two mapping families and all body/tail observations")
}
