//go:build ignore

// Generate portable single-byte tables from independently captured native values.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
	"unicode/utf8"
)

func must(err error) {
	if err != nil {
		panic(err)
	}
}
func read(path string) []byte { b, e := os.ReadFile(path); must(e); return b }
func main() {
	check := flag.Bool("check", false, "verify generated source without changing it")
	flag.Parse()
	data := read("testdata/bundle-removal/plist-legacy-values.json")
	var corpus struct {
		Schema int
		Source string `json:"source_sha256"`
		Codecs []struct {
			Name    string
			Scalars []rune
		}
	}
	must(json.Unmarshal(data, &corpus))
	driver := sha256.Sum256(read("scripts/probe-removal-legacy-values.go"))
	if corpus.Schema != 1 || len(corpus.Codecs) != 55 || corpus.Source != hex.EncodeToString(driver[:]) {
		panic("incomplete or stale native byte evidence")
	}
	slices.SortFunc(corpus.Codecs, func(a, b struct {
		Name    string
		Scalars []rune
	}) int { return strings.Compare(a.Name, b.Name) })
	var tables [][128]rune
	indices := map[[128]rune]int{}
	names := map[string]bool{}
	var entries strings.Builder
	for _, c := range corpus.Codecs {
		if c.Name == "" || c.Name != strings.ToLower(c.Name) || names[c.Name] || len(c.Scalars) != 256 {
			panic("invalid codec inventory")
		}
		names[c.Name] = true
		var table [128]rune
		for i, r := range c.Scalars {
			if i < 128 {
				if r != rune(i) {
					panic("non-ASCII-compatible codec")
				}
			} else {
				if r != -1 && !utf8.ValidRune(r) {
					panic("invalid scalar")
				}
				table[i-128] = r
			}
		}
		index, ok := indices[table]
		if !ok {
			index = len(tables)
			indices[table] = index
			tables = append(tables, table)
		}
		fmt.Fprintf(&entries, "%q: &legacyRunes[%d],\n", c.Name, index)
	}
	sum := sha256.Sum256(data)
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/generate-plist-legacy.go; DO NOT EDIT.\n// Native byte corpus SHA-256: %x\n// ASCII bytes are identity mappings; -1 denotes native conversion failure.\npackage plist\n\nvar legacyCharsets = map[string]*[128]rune{\n%s}\n\nvar legacyRunes = [...][128]rune{\n", sum, entries.String())
	for _, table := range tables {
		out.WriteString("{\n")
		for i, r := range table {
			fmt.Fprintf(&out, "%#x,", r)
			if i%8 == 7 {
				out.WriteByte('\n')
			}
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	generated, e := format.Source([]byte(out.String()))
	must(e)
	const path = "pkg/plist/legacy_tables.go"
	if *check {
		if !bytes.Equal(read(path), generated) {
			panic("stale generated legacy tables")
		}
	} else {
		must(os.WriteFile(path, generated, 0644))
	}
	fmt.Printf("Verified %d charset names and %d distinct native tables\n", len(names), len(tables))
}
